name: Build LHM
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet Packages
        run: nuget restore LibreHardwareMonitor.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild LibreHardwareMonitor.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LHM-Test-Build
          path: |
            bin/Release/
            !bin/Release/**/*.pdb
